language: python
env:
  - TOXENV=py27-dj15
  - TOXENV=py27-dj16
  - TOXENV=py33-dj15
  - TOXENV=py33-dj16
  - TOXENV=flake8
  - TOXENV=sphinx
  - TOXENV=readme
install:
  - pip install tox
script:
  - tox
